[workspace]
members = [
    "examples/ownable",
    "examples/erc20",
    "access_control",
    "tests",
    "libs"
]

# enable overflow checks to make it behave like we used SafeMath in solidity
[profile.release]
overflow-checks = true
lto = true
codegen-units = 1
opt-level="z"